---
  - name: amavisd-new | Install amavisd-new, SpamAssassin and ClamAV
    apt: pkg={{ item }} state=present
    with_items:
      - amavisd-new
      - spamassassin
# cat spam.txt |pyzor 
#      - pyzor
# http://wiki.apache.org/spamassassin/RazorAmavisd
# http://wiki.apache.org/spamassassin/RazorSiteWide
#      - razor
      - clamav-daemon
      - libmail-dkim-perl

  # For 'rar', 'unrar' and 'lha' you need to add contrib and non-free repositories 
  # (and also edit amavis config files)
  - name: amavisd-new | Install unpack utilites
    apt: pkg={{ item }} state=present
    with_items: ['arj', 'bzip2', 'cabextract', 'cpio', 'file', 'gzip', 'nomarch', 'pax', 'unzip', 'zip', 'zoo']

  - name: amavisd-new | Add user clamav to amavis group
    user: name=clamav groups=amavis append=yes
    notify: restart clamav

  - name: amavisd-new | Add user amavis to clamav group
    user: name=amavis groups=clamav append=yes
    notify: restart amavis

  - name: amavisd-new | Create /etc/amavis/dkim folder
    file: path=/etc/amavis/dkim state=directory

  - name: amavisd-new | Create keys for DKIM signing
    command: /usr/sbin/amavisd-new genrsa /etc/amavis/dkim/{{ hostname_fqdn }}.pem creates=/etc/amavis/dkim/{{ hostname_fqdn }}.pem    
    notify: restart amavis

  - name: amavisd-new | Enable spam and virus checks
    template: src=amavis/conf.d/15-content_filter_mode.j2 dest=/etc/amavis/conf.d/15-content_filter_mode mode=0644 owner=root group=root
    notify: restart amavis

  - name: amavisd-new | Configure amavis
    template: src=amavis/conf.d/50-user.j2 dest=/etc/amavis/conf.d/50-user mode=0644 owner=root group=root
    notify: restart amavis

  - name: amavisd-new | Create mysql database
    mysql_db: name={{ amavis_db_name }} encoding=utf8 collation=utf8_unicode_ci state=present
    notify: 
      - copy amavis sql
      - run amavis import

  - name: amavisd-new | Create mysql user
    mysql_user: name={{ amavis_db_username }} password={{ amavis_db_password }} priv={{ amavis_db_name }}.*:ALL state=present

  - name: amavisd-new | Install database cleanup script into /etc/cron.daily
    template: src=amavis/cron.j2 dest=/etc/cron.daily/amavis mode=0700 owner=root group=root

  - name: amavisd-new | Configure SpamAssassin 1
    lineinfile: dest=/etc/spamassassin/local.cf line="score DKIM_VERIFIED -1"

  - name: amavisd-new | Configure SpamAssassin 2
    lineinfile: dest=/etc/spamassassin/local.cf line="score DKIM_SIGNED    0"

  - name: amavisd-new | Start clamav daemon during boot
    service: name=clamav-daemon enabled=yes

  - name: amavisd-new | Start amavis daemon during boot
    service: name=amavis enabled=yes


# TODO: update sa rules: http://krischan.eu/index.php/2014/04/21/spamassassin-bug-gpg-validation-failed/
#       Check /etc/cron.daily/spamassassin for info (sa-update-keys home folder etc.)

# Spamassassin daemon is disabled by default
#  - name: amavisd-new | Stop and disable spamassassin service
#    service: name=spamassassin state=stopped enabled=no
  
# To enable AWL edit /etc/spamassassin/v310.pre and uncomment:
# loadplugin Mail::SpamAssassin::Plugin::AWL
# Edit /etc/spamassassin/local.cf and add:
# use_auto_whitelist 1
