---
  - name: Set hostname
    hostname: name={{ hostname_name }}
    tags: hostname
  
  - name: Update /etc/hosts with a FQDN
    lineinfile:
      dest=/etc/hosts
      regexp="^127\.0\.1\.1"
      line="127.0.1.1{% if hostname_name != hostname_fqdn %}{{'\t'}}{{ hostname_fqdn }}{% endif %}{{'\t'}}{{ hostname_name }}"
      state=present
    tags: hostname
