---
  - name: PHP5 | Install PHP packages
    apt: pkg={{ item }} state=present
    with_items:
      - php5-cli
      - php5-fpm
      - php5-curl
      - php5-mysqlnd
      - php5-intl
      - php5-mcrypt
      - php-apc

  - name: PHP5 | Set custom PHP settings
    template: src=custom.ini.j2 dest=/etc/php5/mods-available/custom.ini mode=0644
    notify:
      - restart php5-fpm

  - name: PHP5 | Link FPM conf.d to custom PHP settings
    action: file src=/etc/php5/mods-available/custom.ini dest=/etc/php5/fpm/conf.d/99-custom.ini state=link
    notify:
      - restart php5-fpm

  - name: PHP5 | Link CLI conf.d to custom PHP settings
    action: file src=/etc/php5/mods-available/custom.ini dest=/etc/php5/cli/conf.d/99-custom.ini state=link

  - name: Start php5-fpm service
    service: name=php5-fpm state=started enabled=yes
